#ifndef CONNECTIONLIBRARY_GLOBAL_H
#define CONNECTIONLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONNECTIONLIBRARY_LIBRARY)
#  define CONNECTION_LIBRARY Q_DECL_EXPORT
#else
#  define CONNECTION_LIBRARY Q_DECL_IMPORT
#endif

#endif // CONNECTIONLIBRARY_GLOBAL_H
